/*
 * gui.c
 *
 *  Created on: 11 февр. 2018 г.
 *      Author: beslan
 */

/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "gui.h"

// GListeners
GListener glistener;

// GHandles
// GHandles
GHandle ghContainerMainPage;
GHandle GW1;
GHandle ghTemperatureText, ghHumidityText;
GHandle ghFan, ghLamp;
GHandle ghTemperature, ghHumidity, ghTemp2;
GHandle ghFanText, ghLampText, ghTemp2Text;

// Fonts
font_t dejavu_sans_16;

static void createPageMainPage(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerMainPage
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerMainPage = gwinContainerCreate(0, &wi, 0);

	// Create console widget: GW1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = ghContainerMainPage;
	GW1 = gwinConsoleCreate(0, &wi.g);
	gwinSetColor(GW1, White);
	gwinSetBgColor(GW1, Black);

}


void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerMainPage);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerMainPage);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DEJAVUSANS16");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);

	// Create all the display pages
	createPageMainPage();

	// Select the default display page
	guiShowPage(0);

	// Console sample text
//	gwinPrintf(GW1, "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet");
}

void guiEventLoop(void)
{
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
		}

	}
}



void uGFXMain(void)
{

}
