/*
 * gui.c
 *
 *  Created on: 11 февр. 2018 г.
 *      Author: beslan
 */

/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "gui.h"

// GListeners
GListener glistener;

// GHandles
// GHandles
GHandle ghContainerMainPage;
GHandle GW1;
GHandle   ghList1;
// Fonts
font_t dejavu_sans_16;

static void createPageMainPage(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerMainPage
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 320;
	wi.g.height = 240;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerMainPage = gwinContainerCreate(0, &wi, 0);

	// Create console widget: GW1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 150;
	wi.g.width = 320;
	wi.g.height = 100;
	wi.g.parent = ghContainerMainPage;
	GW1 = gwinConsoleCreate(0, &wi.g);
//	gwinSetColor(GW1, Black);
//	gwinSetBgColor(GW1, White);

	// Apply the list parameters
	wi.g.show = TRUE;
	wi.g.width = 200;
	wi.g.height = 100;
	wi.g.y = 10;
	wi.g.x = 10;
	wi.text = "List Name";

	// Create the actual list
	ghList1 = gwinListCreate(NULL, &wi, FALSE);


}


void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerMainPage);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerMainPage);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_16 = gdispOpenFont("DEJAVUSANS16");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_16);

	// Create all the display pages
	createPageMainPage();

	// Select the default display page
	guiShowPage(0);

	// Console sample text
//	gwinPrintf(GW1, "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet");
}

void guiEventLoop(void)
{
	GEvent* pe;
	GEventToggle *toogle;
	gwinAttachToggle(ghList1, 0, 0);
	gwinAttachToggle(ghList1, 1, 1);

	geventListenerInit(&glistener);
	if(geventAttachSource(&glistener, ginputGetToggle(1), 1)){
		gwinPrintf(GW1, "Attach\n");
	}
//	geventAttachSource(&glistener, ginputGetToggle(0), GINPUT_TOGGLE_UP);
//	gwinAttachListener(&glistener);
	while (1) {
		// Get an event
		toogle = (GEventToggle *)geventEventWait(&glistener, TIME_INFINITE);
		gwinPrintf(GW1, "ewent %d\n", toogle->on);
//		switch (pe->type) {
//		}

	}
}



void uGFXMain(void)
{

}
